/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: () => void;
export const __wbg_privateinputs_free: (a: number, b: number) => void;
export const __wbg_publicinputs_free: (a: number, b: number) => void;
export const __wbg_output_free: (a: number, b: number) => void;
export const __wbg_proofinputs_free: (a: number, b: number) => void;
export const __wbg_proofresult_free: (a: number, b: number) => void;
export const privateinputs_new: (a: bigint, b: number, c: number, d: number, e: number, f: number, g: any, h: any) => number;
export const privateinputs_r: (a: number) => [number, number];
export const privateinputs_sk_spend: (a: number) => [number, number];
export const privateinputs_leaf_index: (a: number) => number;
export const privateinputs_merkle_path_elements: (a: number) => any;
export const privateinputs_merkle_path_indices: (a: number) => any;
export const publicinputs_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: bigint) => number;
export const publicinputs_root: (a: number) => [number, number];
export const publicinputs_nf: (a: number) => [number, number];
export const publicinputs_outputs_hash: (a: number) => [number, number];
export const output_new: (a: number, b: number, c: bigint) => number;
export const output_address: (a: number) => [number, number];
export const output_amount: (a: number) => bigint;
export const proofinputs_new: (a: number, b: number, c: any) => number;
export const __wbg_sp1wasmprover_free: (a: number, b: number) => void;
export const sp1wasmprover_new: () => number;
export const sp1wasmprover_set_program_vk: (a: number, b: number, c: number) => [number, number];
export const sp1wasmprover_generate_proof: (a: number, b: number) => any;
export const sp1wasmprover_is_ready: (a: number) => number;
export const sp1wasmprover_get_program_vk: (a: number) => [number, number];
export const proofresult_success: (a: number) => number;
export const proofresult_proof: (a: number) => [number, number];
export const proofresult_public_inputs: (a: number) => [number, number];
export const proofresult_error: (a: number) => [number, number];
export const bytes_to_hex: (a: number, b: number) => [number, number];
export const hex_to_bytes: (a: number, b: number) => [number, number, number, number];
export const wasm_prover_health_check: () => number;
export const get_version: () => [number, number];
export const publicinputs_amount: (a: number) => bigint;
export const privateinputs_amount: (a: number) => bigint;
export const proofresult_generation_time_ms: (a: number) => bigint;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_6: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const closure36_externref_shim: (a: number, b: number, c: any) => void;
export const closure51_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
